# src/processor/train_data.py

# -----------------------------
# 50 examples per category
# -----------------------------
train_texts = [
    # ----------------- Ransomware (50) -----------------
    "New ransomware attack encrypts hospital systems across Europe",
    "Ransomware gang targets US schools demanding Bitcoin payments",
    "Hospitals in Germany hit by ransomware causing service delays",
    "Ransomware attack disrupts critical infrastructure in France",
    "CryptoLocker ransomware resurfaces, affecting small businesses",
    "Ransomware spreads through phishing emails, locking files",
    "City council falls victim to ransomware, operations halted",
    "Ransomware campaign targets government networks in Asia",
    "Law enforcement issues warning about new ransomware variants",
    "Healthcare providers struggle with ransomware threats",
    "Ransomware attack shuts down major manufacturing plant",
    "Financial institutions hit by ransomware demanding ransom",
    "Ransomware infiltrates remote work systems via VPN exploits",
    "University campuses affected by ransomware attacks",
    "Ransomware group leaks sensitive data after attack",
    "New ransomware strain detected affecting Windows servers",
    "Municipal networks crippled by ransomware campaign",
    "Ransomware attack hits logistics company causing delays",
    "Phishing emails deliver ransomware to unsuspecting users",
    "Critical servers encrypted by ransomware in US hospital",
    "Ransomware actors demand cryptocurrency to unlock data",
    "Industrial control systems under ransomware threat",
    "Ransomware spreads via malicious email attachments",
    "New ransomware family targets Linux servers",
    "Ransomware attack impacts multiple city departments",
    "Government agencies face ransomware intrusion attempts",
    "Ransomware infection causes shutdown of key IT systems",
    "Ransomware attack causes outage at utility provider",
    "Ransomware gang claims responsibility for hospital breach",
    "Schools and universities targeted by ransomware campaigns",
    "Ransomware delivered via compromised software updates",
    "Corporate networks disrupted by new ransomware strain",
    "Ransomware attacks increase during holiday season",
    "Cybercriminals deploy ransomware against hospitals",
    "Ransomware spreads through unpatched remote desktop systems",
    "Law enforcement collaborates to mitigate ransomware threat",
    "Ransomware encryption hits critical government data",
    "Small businesses suffer losses due to ransomware attacks",
    "Ransomware campaign targets energy sector globally",
    "Attackers use ransomware to extort major corporations",
    "Ransomware infiltrates enterprise networks unnoticed",
    "Healthcare ransomware attack affects patient care",
    "New ransomware variant targets cloud storage systems",
    "Ransomware delivered via malicious email links",
    "Municipal government systems hit by ransomware",
    "Ransomware attack locks files across multiple servers",
    "Cybersecurity experts warn about rising ransomware threats",
    "Ransomware group exploits vulnerabilities in outdated software",
    "Financial services company hit by ransomware attack",
    "Ransomware campaign disrupts IT operations worldwide",

    # ----------------- Data Breach (50) -----------------
    "Customer data exposed in large retail chain breach",
    "Healthcare provider suffers major data breach affecting patients",
    "Bank discloses breach affecting thousands of accounts",
    "Data breach at tech company exposes user passwords",
    "Social media platform reports security breach",
    "Government agency hit by data breach, personal records leaked",
    "Email provider suffers breach, users urged to change passwords",
    "Corporate breach exposes sensitive internal documents",
    "Data breach compromises login credentials of employees",
    "University announces data breach of student information",
    "Retailer confirms breach impacting customer credit cards",
    "Data breach at cloud provider exposes stored files",
    "Hackers leak personal data from online platform",
    "Financial firm detects data breach of client accounts",
    "Healthcare app suffers breach of patient medical records",
    "Data breach exposes email addresses and passwords",
    "Law firm reports breach of confidential client data",
    "E-commerce site suffers breach, credit card info stolen",
    "Data breach at payment processor compromises transactions",
    "Company discloses breach affecting employee records",
    "Social networking site hit by major data breach",
    "Breach exposes personal data of millions of users",
    "Data breach targets government contractor",
    "Tech startup suffers breach, source code leaked",
    "Data breach impacts online education platform",
    "Hospital chain reports breach affecting medical data",
    "Financial services firm experiences data breach",
    "Data breach exposes usernames and hashed passwords",
    "Retail chain data breach affects loyalty program members",
    "Company suffers breach of confidential business documents",
    "Data breach at software company exposes client info",
    "Hackers access sensitive personal information",
    "Data breach in banking sector compromises accounts",
    "Healthcare provider leaks patient data in breach",
    "Breach exposes tax records and financial details",
    "Online marketplace suffers data breach of users",
    "Data breach at telecom company reveals call records",
    "University reports breach of alumni database",
    "Data breach impacts cloud storage accounts",
    "Major retailer suffers breach of credit card data",
    "Data breach exposes employee email communications",
    "Hackers leak private messages from social platform",
    "Data breach compromises login info for corporate network",
    "Healthcare system hit by breach, patient privacy affected",
    "Breach exposes confidential government documents",
    "Company confirms breach affecting customer accounts",
    "Data breach affects millions of mobile app users",
    "Breach leaks sensitive legal case documents",
    "Data breach at online payment provider",
    "Hackers exploit breach to steal identity info",
    "Data breach exposes private health information",
    "Tech company experiences major data breach",
    "Breach reveals employee and customer personal info",

    # ----------------- Malware (50) -----------------
    "New malware discovered targeting Windows 10",
    "Trojan infects banking applications on Android devices",
    "Backdoor malware found on corporate servers",
    "Botnet malware spreads via IoT devices",
    "Malware campaign targets enterprise networks",
    "Critical malware affects cloud-hosted servers",
    "MacOS malware infects devices via malicious emails",
    "Malware hides in legitimate software downloads",
    "Banking malware steals credentials from victims",
    "Malware detected in popular mobile applications",
    "Corporate systems compromised by spyware malware",
    "Malware spreads through phishing campaigns",
    "New malware strain bypasses antivirus software",
    "Malware targets critical infrastructure networks",
    "Advanced malware discovered in Linux servers",
    "Malware infection causes disruption in company operations",
    "Malware delivered via infected USB drives",
    "Email attachments carry malware payloads",
    "Malware campaign affects government networks",
    "Mobile malware exploits vulnerabilities in apps",
    "Ransomware malware encrypts important files",
    "Malware infiltrates software supply chain",
    "Corporate malware targets sensitive data",
    "Malware detected in cloud storage services",
    "Mac malware uses keylogging to steal information",
    "Malware exploits zero-day vulnerabilities",
    "Spyware malware tracks user behavior online",
    "Malware affects point-of-sale systems",
    "New malware strain spreads via malicious links",
    "Malware targets healthcare networks",
    "Industrial malware disrupts production lines",
    "Malware detected in IoT cameras",
    "Mobile malware steals banking credentials",
    "Malware hides in pirated software downloads",
    "Corporate networks infected by malware",
    "Malware campaign targets energy sector",
    "Malware exploits outdated software vulnerabilities",
    "Malware spreads through infected email attachments",
    "MacOS malware targets enterprise users",
    "Malware payload causes system shutdowns",
    "Malware steals sensitive intellectual property",
    "Malware detected in open-source projects",
    "Malware attack affects critical servers",
    "Malware delivered via malicious links and ads",
    "Advanced malware targets industrial systems",
    "Malware campaign uses social engineering attacks",
    "Malware discovered in popular productivity apps",
    "Malware targets financial institutions",
    "Malware infiltrates company network unnoticed",
    "New malware family affects multiple operating systems",

    # ----------------- Phishing (50) -----------------
    "Phishing emails target customers of major banks",
    "Spear-phishing campaign attacks company executives",
    "Phishing scam impersonates government agency",
    "Email phishing targets healthcare providers",
    "Phishing attack tricks users into revealing passwords",
    "Fake invoice phishing emails distributed to businesses",
    "Phishing links delivered via social media platforms",
    "Bank phishing emails attempt to steal login info",
    "Corporate phishing emails impersonate CEO",
    "Phishing email campaigns affect university staff",
    "Phishing attacks target online payment platforms",
    "Spear phishing compromises employee credentials",
    "Phishing emails deliver malware attachments",
    "Credential phishing attacks increase globally",
    "Phishing emails trick users into installing spyware",
    "Fake tech support phishing messages sent to users",
    "Phishing attacks impersonate well-known brands",
    "Phishing links in emails steal sensitive data",
    "Phishing email impersonates bank notifications",
    "Business phishing emails lead to account compromise",
    "Phishing messages exploit remote work vulnerabilities",
    "Spear phishing targets HR department emails",
    "Phishing emails attempt to capture personal information",
    "Fake phishing websites trick employees",
    "Phishing attack delivers ransomware via email",
    "Phishing campaign affects cloud service users",
    "Phishing emails target online banking customers",
    "Corporate phishing emails spread malware",
    "Phishing links redirect users to fake login pages",
    "Phishing emails claim to be urgent security alerts",
    "Spear phishing targets finance department staff",
    "Phishing campaign impersonates social media company",
    "Emails containing phishing links bypass filters",
    "Phishing attacks target government contractors",
    "Phishing emails compromise credentials for SaaS platforms",
    "Phishing attacks affect email communications globally",
    "Phishing emails impersonate online retailers",
    "Spear phishing attempts to steal intellectual property",
    "Phishing links lead to credential theft",
    "Phishing emails exploit human errors",
    "Phishing campaigns target cloud storage users",
    "Phishing attacks compromise VPN login credentials",
    "Phishing emails carry malicious attachments",
    "Phishing messages trick employees into sharing passwords",
    "Phishing attacks use social engineering tactics",
    "Phishing emails attempt to hijack online accounts",
    "Spear phishing emails target key personnel",
    "Phishing campaigns deliver malware payloads",
    "Phishing messages impersonate IT security teams",
    "Phishing emails attempt to steal sensitive information",
    "Phishing links delivered via SMS and email",

    # ----------------- Vulnerability (50) -----------------
    "Critical zero-day vulnerability discovered in Windows",
    "CVE-2023-XXXX disclosed affecting Linux systems",
    "Patch released for high-risk vulnerability in popular software",
    "Remote code execution vulnerability found in cloud platform",
    "Unpatched vulnerability allows attackers to escalate privileges",
    "New vulnerability discovered in IoT devices",
    "Critical flaw affects enterprise VPN servers",
    "Vulnerability in popular CMS exposes admin accounts",
    "Security researchers report buffer overflow vulnerability",
    "Web application vulnerability allows SQL injection",
    "Zero-day vulnerability exploited in ransomware attacks",
    "Vulnerability discovered in authentication module",
    "Server vulnerability allows remote takeover",
    "Vulnerability in network devices affects large organizations",
    "Critical security flaw patched in email server software",
    "Vulnerability in third-party library affects applications",
    "Privilege escalation vulnerability discovered in Windows",
    "Vulnerability in mobile apps exposes sensitive data",
    "Security flaw allows bypass of authentication",
    "Critical flaw discovered in VPN client software",
    "Vulnerability in database server exploited in attacks",
    "Zero-day vulnerability patched in popular CMS",
    "Vulnerability discovered in web browser extensions",
    "Remote vulnerability allows command execution",
    "Critical flaw in cloud management software discovered",
    "Vulnerability affects containerized applications",
    "Unpatched vulnerability in email gateway exploited",
    "Vulnerability in firmware allows malware installation",
    "Security flaw in industrial control system discovered",
    "Vulnerability in network monitoring tool exploited",
    "Critical vulnerability affects healthcare applications",
    "New vulnerability in office productivity suite discovered",
    "Vulnerability allows unauthorized access to data",
    "Security flaw in mobile operating system patched",
    "Critical vulnerability exploited in targeted attacks",
    "Vulnerability in virtualization platform reported",
    "Security flaw in authentication process discovered",
    "Critical bug in networking software patched",
    "Vulnerability allows remote access to enterprise servers",
    "New vulnerability in web application framework discovered",
    "Vulnerability in file-sharing software exploited",
    "Security flaw in encryption library reported",
    "Critical vulnerability affects cloud storage users",
    "Vulnerability in network protocol exploited by attackers",
    "Security flaw allows privilege escalation",
    "Critical bug discovered in IoT devices",
    "Vulnerability in VPN appliance patched",
    "Security flaw in SaaS application reported",
    "Critical vulnerability in web server discovered",
    "New vulnerability in mobile banking apps reported",
    "Vulnerability in authentication server patched",
    "Critical security flaw in cloud platform exploited",

    # ----------------- DDoS (50) -----------------
    "DDoS attack targets government websites",
    "Massive DDoS disrupts financial services",
    "Botnet used in distributed denial-of-service attack",
    "DDoS attack overwhelms ISP servers",
    "High-volume DDoS affects gaming platforms",
    "DDoS campaign targets e-commerce websites",
    "Cloud-based DDoS attack mitigated by security teams",
    "DDoS attack disrupts online banking",
    "DDoS attack targets critical infrastructure",
    "IoT devices used in large-scale DDoS attack",
    "DDoS attack against popular social media platform",
    "Mitigation strategies reduce DDoS impact",
    "DDoS attack exploits DNS amplification vulnerability",
    "New DDoS attacks hit cloud providers",
    "DDoS attack affects telecom networks",
    "Record-breaking DDoS floods corporate servers",
    "DDoS attack targets government portals",
    "Multi-vector DDoS campaign observed",
    "DDoS attack impacts online streaming platforms",
    "Cloud service suffers DDoS disruption",
    "DDoS attack on e-government services",
    "DDoS attack affects payment gateways",
    "DDoS attack targeting critical servers",
    "New DDoS mitigation techniques deployed",
    "DDoS attack disrupts healthcare IT systems",
    "IoT botnet launches DDoS campaign",
    "DDoS attack overwhelms cloud network",
    "DDoS attack on major news sites",
    "DDoS attack affects e-learning platforms",
    "DDoS campaign targets financial institutions",
    "DDoS attack disrupts online marketplaces",
    "DDoS attack exploits vulnerable routers",
    "New DDoS attacks impact enterprise networks",
    "DDoS attack hits gaming servers",
    "DDoS attack targets telecom infrastructure",
    "DDoS attack mitigated by cloud firewall",
    "DDoS attack affects retail websites",
    "Massive DDoS targets healthcare portals",
    "DDoS attack exploits IoT botnet",
    "DDoS attack disrupts online communications",
    "DDoS attack hits major cloud providers",
    "DDoS attack targets e-commerce platforms",
    "DDoS attack affects government domains",
    "DDoS attack on popular online services",
    "DDoS attack impacts mobile networks",
    "DDoS attack affects banking websites",
    "DDoS attack targets cloud infrastructure",
    "DDoS attack mitigated by security teams",
    "DDoS attack affects streaming services",
    "DDoS attack exploits amplification techniques",
    "DDoS attack disrupts enterprise operations",
    "DDoS attack targets networked devices",

    # ----------------- Cloud Security (50) -----------------
    "AWS misconfiguration exposes sensitive cloud data",
    "Azure cloud service suffers security incident",
    "GCP cloud platform vulnerability disclosed",
    "Cloud storage misconfiguration leaks user files",
    "Cloud provider patches critical security flaw",
    "Cloud infrastructure compromised by malware",
    "Security breach in cloud-based email service",
    "Cloud security misconfiguration leads to data exposure",
    "Cloud servers exploited by cybercriminals",
    "New cloud security guidelines issued for enterprises",
    "Cloud access credentials leaked online",
    "Cloud vulnerability exploited in targeted attacks",
    "Multi-tenant cloud platform affected by security issue",
    "Cloud application vulnerability discovered",
    "Unauthorized cloud access detected in enterprise systems",
    "Cloud platform misconfiguration causes data breach",
    "Cloud storage vulnerability patched by provider",
    "AWS S3 bucket exposed sensitive data",
    "Cloud security misconfigurations continue to rise",
    "Cloud service disruption due to attack",
    "Critical cloud vulnerability discovered",
    "Cloud infrastructure compromised by threat actors",
    "Cloud platform exploited to host malware",
    "Cloud server misconfiguration exposes client info",
    "New cloud security standards released",
    "Cloud service vulnerability discovered",
    "Cloud misconfiguration leaks private data",
    "Cloud access permissions misconfigured",
    "Security researchers report cloud platform flaw",
    "Cloud providers patch critical vulnerabilities",
    "Cloud system misconfiguration exploited",
    "Cloud service compromised by attackers",
    "Cloud platform security flaw patched",
    "Unauthorized access to cloud servers detected",
    "Cloud platform misconfiguration causes outage",
    "Cloud security alerts issued to customers",
    "Cloud application vulnerability exploited",
    "Cloud servers exposed due to misconfiguration",
    "Cloud system flaw discovered",
    "Cloud environment affected by malware",
    "Cloud credentials stolen by attackers",
    "Cloud storage misconfiguration causes data leak",
    "Cloud security breach affects enterprise data",
    "Cloud platform vulnerability exploited by hackers",
    "Critical cloud misconfiguration discovered",
    "Cloud application flaw patched",
    "Cloud servers exploited by ransomware",
    "Cloud system misconfiguration detected",
    "Cloud access misconfigured in enterprise",
    "Cloud service flaw exploited",
    "Cloud storage vulnerability exposed",
    "New cloud security threat identified",

    # ----------------- Other (50) -----------------
    "Cybersecurity news roundup: top stories this week",
    "Experts discuss latest threats in cybersecurity",
    "Overview of recent malware campaigns",
    "Weekly recap of data breaches",
    "New tools for ethical hacking released",
    "Cybersecurity conference highlights key findings",
    "Updates on vulnerability patches",
    "Report on phishing trends",
    "New reports on DDoS attacks",
    "Security awareness tips for employees",
    "Analysis of cybersecurity legislation",
    "Trends in cloud security adoption",
    "Summary of ransomware incidents",
    "Top cybersecurity research papers this month",
    "Guidelines for secure software development",
    "Highlights from security webinars",
    "Monthly security newsletter",
    "Reports on IoT security challenges",
    "Security advisories for organizations",
    "Best practices in endpoint protection",
    "Updates on cyberattack investigations",
    "Overview of phishing schemes",
    "Critical vulnerabilities summarized",
    "Cybersecurity blog roundup",
    "Analysis of corporate security posture",
    "Summary of malware outbreaks",
    "Security tool reviews and comparisons",
    "Updates on cybersecurity frameworks",
    "Reports on emerging threats",
    "Highlights of security incidents",
    "Security news digest",
    "Insights into hacker tactics",
    "Overview of recent exploits",
    "Security briefings and alerts",
    "Cyber defense recommendations",
    "Updates on network security policies",
    "Weekly malware analysis",
    "Security incident summaries",
    "News on cyber espionage campaigns",
    "Roundup of vulnerability disclosures",
    "Threat intelligence reports",
    "Analysis of ransomware groups",
    "Updates on cloud security incidents",
    "Summaries of phishing campaigns",
    "Cybersecurity industry news",
    "Security training updates",
    "Insights on attack vectors",
    "Reports on critical systems",
    "Overview of cybersecurity best practices",
    "Weekly security updates",
    "Analysis of cyber threats",
]

train_labels = (
    ["ransomware"]*50 +
    ["data breach"]*53 +
    ["malware"]*50 +
    ["phishing"]*51 +
    ["vulnerability"]*52 +
    ["ddos"]*52 +
    ["cloud security"]*52 +
    ["other"]*51
)
